"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";

interface LegalModalProps {
  type: 'terms' | 'privacy' | null;
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ type, onClose }) => {
  if (!type) return null;

  const title = type === 'privacy' ? 'Privacy Policy' : 'Terms of Service';

  return (
    <Dialog open={!!type} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[625px]">
        <DialogHeader>
          <DialogTitle className="text-2xl font-headline">{title}</DialogTitle>
        </DialogHeader>
        <div className="prose prose-sm dark:prose-invert max-h-[60vh] overflow-y-auto pr-4">
          <p>
            This is a demo {title.toLowerCase()}. In a real production application, this would contain the full legal text regarding data collection, usage rights, and user responsibilities.
          </p>
          <p>
            <strong>Data Processing:</strong> StudyGenius stores user data on Firebase (a Google service) and processes study materials via the Google Gemini API. Your data is subject to Google's privacy policies and terms of service in addition to our own.
          </p>
          <p>
            <strong>User Responsibilities:</strong> You are responsible for the content you upload and must ensure you have the rights to use it. Do not upload sensitive personal information.
          </p>
          <p>
            <strong>Disclaimer:</strong> The study materials generated by AI may not be 100% accurate. Always verify critical information with reliable sources.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
};
